list: $/uit/content/models/step/columns.yaml
modelClass: Uit\Content\Models\Step
title: Steps
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'uit/content/steps/update/:id'
