title: Статьи
modelClass: Uit\Content\Models\Post
list: $/uit/content/models/post/columns.yaml
recordUrl: 'uit/content/posts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
