title: Вакансии
modelClass: Uit\Content\Models\Job
list: $/uit/content/models/job/columns.yaml
recordUrl: 'uit/content/jobs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
