title: Видео
modelClass: Uit\Content\Models\Video
list: $/uit/content/models/video/columns.yaml
recordUrl: 'uit/content/videos/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
