title: Страницы
modelClass: Uit\Content\Models\Page
list: $/uit/content/models/page/columns.yaml
recordUrl: 'uit/content/pages/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
