title: Вопросы
modelClass: Uit\Content\Models\Faq
list: $/uit/content/models/faq/columns.yaml
recordUrl: 'uit/content/faqs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
