title: Спецпредложения
modelClass: Uit\Content\Models\Special
list: $/uit/content/models/special/columns.yaml
recordUrl: 'uit/content/specials/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
